### ISSUE TITLE
Publish package from GitHub Actions

### ISSUE THREAD

**Issue by melroy89** [fake-useragent/fake-useragent#137]
Next step is to publish the Python packages to PyPi. Needs a dependency on the tests! Tests should all be passing before releasing as well. 

@hellysmile Please give me more rights so I can access the GitHub repo settings in order to add GitHub Action Secrets.

![settings](https://user-images.githubusercontent.com/628926/199611352-b6d8967d-3b2d-422d-8d02-15d87a1bc35b.png)

Example given by GitHub:

```yml
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
```
