### ISSUE TITLE
Package cache json file locally

### ISSUE THREAD

**Issue by melroy89** [fake-useragent/fake-useragent#150]
Add (using GitHub Actions/part of the pipeline) cache file to the repo. Store within the `data` sub-directory of the `fake-useragent` directory.

Add to `pyproject.toml` file:

```toml
[tool.setuptools.package-data]
"fake-useragent.data" = ["*.json"]
```

Using importlib to retrieve the data file:

```py
try:
  from importlib.resources import files
except ImportError:
  from importlib_resources import files

local_data = files('fake-useragent.data').joinpath('cache.json').read_text()
```

And add the data folder to [PyPi package as data files](https://setuptools.pypa.io/en/stable/userguide/datafiles.html).
